export const PHASE1_INSTRUCTIONS = 'PHASE1_INSTRUCTIONS';
export const PHASE1_PRACTICE = 'PHASE1_PRACTICE';
export const PHASE1_INTRODUCTION = 'PHASE1_INTRODUCTION';
export const PHASE1 = 'PHASE1';
export const PHASE2_INSTRUCIONS = 'PHASE2_INSTRUCIONS';
export const PHASE2 = 'PHASE2';
export const PHASE3_INSTRUCIONS = 'PHASE3_INSTRUCIONS';
export const PHASE3 = 'PHASE3';
export const QUESTIONNAIRE = 'QUESTIONNAIRE';

export const PHASE_FLOW = [PHASE1_INSTRUCTIONS, PHASE1_PRACTICE, PHASE1_INTRODUCTION, PHASE1, PHASE2_INSTRUCIONS, PHASE2, PHASE3_INSTRUCIONS, PHASE3, QUESTIONNAIRE];