export const LOGIN_PAGE = 'LOGIN_PAGE';
export const PHASE1_PRACTICE_INSTRUCTIONS = 'PHASE1_PRACTICE_INSTRUCTIONS';
export const PHASE1_PRACTICE = 'PHASE1_PRACTICE';
export const PHASE1_INSTRUCTIONS = 'PHASE1_INSTRUCTIONS';
export const PHASE1 = 'PHASE1';
export const PHASE2_INSTRUCTIONS = 'PHASE2_INSTRUCTIONS';
export const PHASE2_PRACTICE_INSTRUCTIONS = 'PHASE2_PRACTICE_INSTRUCTIONS';
export const PHASE2_PRACTICE = 'PHASE2_PRACTICE';
export const PHASE2 = 'PHASE2';
export const PHASE3_INSTRUCTIONS = 'PHASE3_INSTRUCTIONS';
export const PHASE3 = 'PHASE3';
export const QUESTIONNAIRE = 'QUESTIONNAIRE';
export const PHASE_END_INSTRUCTIONS = 'PHASE_END_INSTRUCTIONS';

export const PHASE_FLOW = [
	LOGIN_PAGE,
	PHASE1_PRACTICE_INSTRUCTIONS,
	PHASE1_PRACTICE,
	PHASE1_INSTRUCTIONS,
	PHASE1,
	PHASE2_PRACTICE_INSTRUCTIONS,
	PHASE2_PRACTICE,
	PHASE2_INSTRUCTIONS,
	PHASE2,
	PHASE3_INSTRUCTIONS,
	PHASE3,
	QUESTIONNAIRE,
	PHASE_END_INSTRUCTIONS
];

export const RULE_TO_KEY = {
  Blue: {
    "Accept Fish": 'KeyX',
    "Reject Fish": 'KeyC',
    "Reject Crab": 'KeyN',
    "Accept Crab": 'KeyM'
  },
  Orange: {
    "Reject Fish": 'KeyX',
    "Accept Fish": 'KeyC',
    "Accept Crab": 'KeyN',
    "Reject Crab": 'KeyM'
  }
};