export const PAGE_GALLERY_SUBSIDY = 'PAGE_GALLERY_SUBSIDY';
export const PAGE_GALLERY_TAX = 'PAGE_GALLERY_TAX';
export const PAGE_KEY_SELECT_SUBSIDY = 'PAGE_KEY_SELECT_SUBSIDY';
export const PAGE_KEY_SELECT_TAX = 'PAGE_KEY_SELECT_TAX';
export const PAGE_KEY_SELECT_OUTCOME = 'PAGE_KEY_SELECT_OUTCOME';
export const PAGE_CONFIDENCE_SUBSIDY = 'PAGE_CONFIDENCE_SUBSIDY';
export const PAGE_CONFIDENCE_TAX = 'PAGE_CONFIDENCE_TAX';

export const PAGE_FLOW = [
	PAGE_GALLERY_SUBSIDY,
	PAGE_KEY_SELECT_SUBSIDY,
	PAGE_CONFIDENCE_SUBSIDY,
	PAGE_GALLERY_TAX,
	PAGE_KEY_SELECT_TAX,
	PAGE_CONFIDENCE_TAX,
	PAGE_KEY_SELECT_OUTCOME];
